name: Auto CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy2', 'pypy3' ] 
    outputs:
      moduleDir: ${{ steps.auto-ci.outputs.moduleDir}}
      info: ${{ steps.auto-ci.outputs.info}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
            cache-name: cache-node-modules
        with:
            # npm cache files are stored in `~/.npm` on Linux/macOS
            path: node_modules
            key: ${{ runner.os }}-${{ hashFiles('**/yarn-lock.json') }}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install sam
        #run: wget https://files.pythonhosted.org/packages/8a/6c/e1bacac1d9de433f77edf3d94514736876ad599fc70b1ce994d3cbd419c0/aws_sam_cli-1.6.2-py3-none-any.whl && pip3 install setuptools && pip3 install wheel pip3 install aws_sam_cli-1.6.2-py3-none-any.whl
        run: pip install aws-sam-cli
      - name: auto-ci
        id: auto-ci
        uses: wangziling100/AutoCI@v1.0.8
        with:
          configPath: .github/autoCI.config.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          SAM_CLI_TELEMETRY: 0